const _ = require('lodash');
const dataSources = require('./lib/dataSources');

function annotateDataSources(dataSources, key) {
  if (isAccessSchema(dataSources)) {
    return annotateAccessSchema(dataSources, key);
  } else if (_.isFunction(dataSources)) {
    return annotateBuilder(dataSources, key);
  } else if (_.isObject(dataSources)) {
    _.each(dataSources, (v, k) => {
      annotateDataSources(v, `${key}.${k}`);
    });
  }
}

function isAccessSchema(dataSource) {
  return _.get(dataSource, 'dataSource')
}

function annotateAccessSchema(accessSchema, key) {
  console.log(`*${key}*: ${accessSchema.name}\n`);
  console.log(` dataSource: \`${accessSchema.dataSource}\`\n`);
  console.log(` requiredParams:\n`);
  _.each(accessSchema.requiredParams, (v, k) => {
   console.log(`  ${k} : ${v.description || ''}\n`);
  });
  console.log(` optionalParams:\n`);
  _.each(accessSchema.optionalParams, (v, k) => {
   console.log(`  ${k} : ${v.description || ''}\n`);
  });
}

function annotateBuilder(builder, key) {
}

console.log('## Builtin Data Sources');
console.log('This file is autogenerated by `npm run docs`\n\n\n');
annotateDataSources(dataSources, 'dataSources', 0);
